### ISSUE TITLE
No image displaying

### ISSUE THREAD

**Issue by gndumbri** [rrwen/google_streetview#10]
Hello,

When I run the code:

```
params = [{
	'size': '600x300', 
	'location': '35.124762,-89.990795',
	'heading': '151.78',
	'pitch': '-0.76',
	'key': 'KEY NOT SHARED HERE'
}]

results = google_streetview.api.results(params)
results.preview()
```

It does not display an image. I am running this code in Google Colab. Here is what I get instead:
```
[0] DcLKdIVOjVWy1jDDui2kDA
===========================
date: 2019-06
location: 
  lat: 35.12474824026881
  lng: -89.99079815233901
pano_id: DcLKdIVOjVWy1jDDui2kDA
status: OK
```

How do I get the image from google street view to appear?
